"""initial PrepBuddy schema

Revision ID: 20260830_0001
Revises:
Create Date: 2026-08-30 22:12:20.457645
"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

from alembic import op

revision: str = "20260830_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_occupations",
        sa.Column("taxonomy", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("preferred_label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_external_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_occupations")),
        sa.UniqueConstraint(
            "taxonomy", "external_id", name="uq_taxonomy_occupations_taxonomy_external_id"
        ),
    )
    op.create_table(
        "taxonomy_skills",
        sa.Column("taxonomy", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("skill_category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_skills")),
        sa.UniqueConstraint(
            "taxonomy", "canonical_name", name="uq_taxonomy_skills_taxonomy_canonical_name"
        ),
        sa.UniqueConstraint(
            "taxonomy", "external_id", name="uq_taxonomy_skills_taxonomy_external_id"
        ),
    )
    op.create_table(
        "users",
        sa.Column("auth_provider_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_provider_subject", name=op.f("uq_users_auth_provider_subject")),
    )
    op.create_table(
        "candidates",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("current_role", sa.String(length=200), nullable=True),
        sa.Column("experience_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experience_years IS NULL OR experience_years >= 0",
            name=op.f("ck_candidates_experience_years_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_candidates_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
    )
    op.create_index("ix_candidates_user_id", "candidates", ["user_id"], unique=False)
    op.create_table(
        "skill_aliases",
        sa.Column("taxonomy_skill_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_skill_id"],
            ["taxonomy_skills.id"],
            name=op.f("fk_skill_aliases_taxonomy_skill_id_taxonomy_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_aliases")),
        sa.UniqueConstraint(
            "taxonomy_skill_id", "normalized_alias", name=op.f("uq_skill_aliases_taxonomy_skill_id")
        ),
    )
    op.create_table(
        "taxonomy_occupation_skills",
        sa.Column("taxonomy_occupation_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_skill_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("importance", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "importance IS NULL OR importance BETWEEN 0 AND 1",
            name=op.f("ck_taxonomy_occupation_skills_importance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_occupation_id"],
            ["taxonomy_occupations.id"],
            name=op.f("fk_taxonomy_occupation_skills_taxonomy_occupation_id_taxonomy_occupations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_skill_id"],
            ["taxonomy_skills.id"],
            name=op.f("fk_taxonomy_occupation_skills_taxonomy_skill_id_taxonomy_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_occupation_skills")),
        sa.UniqueConstraint(
            "taxonomy_occupation_id",
            "taxonomy_skill_id",
            "relationship_type",
            name=op.f("uq_taxonomy_occupation_skills_taxonomy_occupation_id"),
        ),
    )
    op.create_table(
        "candidate_target_roles",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_occupation_id", sa.UUID(), nullable=True),
        sa.Column("role_name", sa.String(length=200), nullable=False),
        sa.Column("role_family", sa.String(length=120), nullable=True),
        sa.Column("priority", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority > 0", name=op.f("ck_candidate_target_roles_priority_positive")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_target_roles_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_occupation_id"],
            ["taxonomy_occupations.id"],
            name=op.f("fk_candidate_target_roles_taxonomy_occupation_id_taxonomy_occupations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_target_roles")),
        sa.UniqueConstraint(
            "candidate_id", "role_name", name=op.f("uq_candidate_target_roles_candidate_id")
        ),
    )
    op.create_table(
        "clustering_runs",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                name="clustering_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("input_jobs_count", sa.Integer(), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "input_jobs_count >= 0", name=op.f("ck_clustering_runs_input_jobs_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_clustering_runs_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clustering_runs")),
    )
    op.create_index(
        "ix_clustering_runs_candidate_started",
        "clustering_runs",
        ["candidate_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "clusters",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "LOW_PRIORITY",
                "ARCHIVED",
                name="cluster_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("user_locked", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_clusters_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
    )
    op.create_index(
        "ix_clusters_candidate_status", "clusters", ["candidate_id", "status"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "CV",
                "JOB_DESCRIPTION",
                name="document_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_source_documents_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "candidate_id",
            "document_type",
            "content_hash",
            name=op.f("uq_source_documents_candidate_id"),
        ),
    )
    op.create_index(
        "ix_source_documents_candidate_status",
        "source_documents",
        ["candidate_id", "status"],
        unique=False,
    )
    op.create_table(
        "user_corrections",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("previous_value", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("corrected_value", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_user_corrections_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_corrections")),
    )
    op.create_index(
        "ix_user_corrections_entity", "user_corrections", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "cluster_versions",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("clustering_run_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generated_name", sa.String(length=255), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="cluster_confidence",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "common_responsibilities",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "common_tools",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "common_interview_topics",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "market_signal_summary",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_cluster_versions_confidence_score_range"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_cluster_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_cluster_versions_cluster_id_clusters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["clustering_run_id"],
            ["clustering_runs.id"],
            name=op.f("fk_cluster_versions_clustering_run_id_clustering_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_versions")),
        sa.UniqueConstraint("cluster_id", "version", name=op.f("uq_cluster_versions_cluster_id")),
    )
    op.create_index(
        "uq_cluster_versions_one_active",
        "cluster_versions",
        ["cluster_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "evidence_references",
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_evidence_references_confidence_range"),
        ),
        sa.CheckConstraint(
            "start_offset IS NULL OR end_offset IS NULL OR end_offset >= start_offset",
            name=op.f("ck_evidence_references_valid_offsets"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_evidence_references_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_references")),
    )
    op.create_index(
        "ix_evidence_references_entity",
        "evidence_references",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "extraction_runs",
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                name="extraction_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("raw_output", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_extraction_runs_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
    )
    op.create_index(
        "ix_extraction_runs_document_started",
        "extraction_runs",
        ["source_document_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "job_descriptions",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("application_status", sa.String(length=50), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_job_descriptions_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_job_descriptions_source_document_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_descriptions")),
        sa.UniqueConstraint(
            "source_document_id", name=op.f("uq_job_descriptions_source_document_id")
        ),
    )
    op.create_index(
        "ix_job_descriptions_candidate_created",
        "job_descriptions",
        ["candidate_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "prep_plans",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_prep_plans_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_prep_plans_cluster_id_clusters"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prep_plans")),
    )
    op.create_index(
        "ix_prep_plans_candidate_archived",
        "prep_plans",
        ["candidate_id", "is_archived"],
        unique=False,
    )
    op.create_table(
        "candidate_profile_versions",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("extraction_run_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("current_role", sa.String(length=200), nullable=True),
        sa.Column("experience_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column(
            "projects",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "domains",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "achievements",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "seniority_signals",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "is_user_confirmed", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_candidate_profile_versions_confidence_range"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_candidate_profile_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_profile_versions_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_candidate_profile_versions_extraction_run_id_extraction_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_candidate_profile_versions_source_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profile_versions")),
        sa.UniqueConstraint(
            "candidate_id", "version", name=op.f("uq_candidate_profile_versions_candidate_id")
        ),
    )
    op.create_index(
        "uq_candidate_profile_versions_one_active",
        "candidate_profile_versions",
        ["candidate_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "cluster_skill_summaries",
        sa.Column("cluster_version_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_skill_id", sa.UUID(), nullable=True),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column(
            "skill_type",
            sa.Enum(
                "CORE",
                "SECONDARY",
                "WEAK_SIGNAL",
                "REQUIRED",
                "NICE_TO_HAVE",
                name="cluster_skill_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "frequency BETWEEN 0 AND 1", name=op.f("ck_cluster_skill_summaries_frequency_range")
        ),
        sa.CheckConstraint(
            "job_count >= 0", name=op.f("ck_cluster_skill_summaries_job_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["cluster_version_id"],
            ["cluster_versions.id"],
            name=op.f("fk_cluster_skill_summaries_cluster_version_id_cluster_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_skill_id"],
            ["taxonomy_skills.id"],
            name=op.f("fk_cluster_skill_summaries_taxonomy_skill_id_taxonomy_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_skill_summaries")),
        sa.UniqueConstraint(
            "cluster_version_id",
            "normalized_name",
            "skill_type",
            name=op.f("uq_cluster_skill_summaries_cluster_version_id"),
        ),
    )
    op.create_table(
        "job_profile_versions",
        sa.Column("job_description_id", sa.UUID(), nullable=False),
        sa.Column("extraction_run_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("seniority", sa.String(length=100), nullable=True),
        sa.Column("role_family", sa.String(length=150), nullable=True),
        sa.Column("domain", sa.String(length=150), nullable=True),
        sa.Column("work_style", sa.String(length=100), nullable=True),
        sa.Column("ai_relevance", sa.Float(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=200), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "ai_relevance IS NULL OR ai_relevance BETWEEN 0 AND 1",
            name=op.f("ck_job_profile_versions_ai_relevance_range"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_job_profile_versions_confidence_range"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_job_profile_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_job_profile_versions_extraction_run_id_extraction_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_description_id"],
            ["job_descriptions.id"],
            name=op.f("fk_job_profile_versions_job_description_id_job_descriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_profile_versions")),
        sa.UniqueConstraint(
            "job_description_id", "version", name=op.f("uq_job_profile_versions_job_description_id")
        ),
    )
    op.create_index(
        "uq_job_profile_versions_one_active",
        "job_profile_versions",
        ["job_description_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "market_signal_snapshots",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("cluster_version_id", sa.UUID(), nullable=True),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column("jobs_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jobs_count >= 0", name=op.f("ck_market_signal_snapshots_jobs_count_non_negative")
        ),
        sa.CheckConstraint(
            "window_end >= window_start", name=op.f("ck_market_signal_snapshots_valid_window")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_market_signal_snapshots_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_version_id"],
            ["cluster_versions.id"],
            name=op.f("fk_market_signal_snapshots_cluster_version_id_cluster_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_signal_snapshots")),
    )
    op.create_index(
        "ix_market_signal_snapshots_candidate_window",
        "market_signal_snapshots",
        ["candidate_id", "window_end"],
        unique=False,
    )
    op.create_table(
        "candidate_skills",
        sa.Column("candidate_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_skill_id", sa.UUID(), nullable=True),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column(
            "skill_type",
            sa.Enum(
                "CORE",
                "SECONDARY",
                "WEAK_SIGNAL",
                "REQUIRED",
                "NICE_TO_HAVE",
                name="candidate_skill_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("proficiency", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "CV",
                "JOB_DESCRIPTION",
                "USER",
                "TAXONOMY",
                "SYSTEM",
                name="candidate_skill_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_candidate_skills_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_version_id"],
            ["candidate_profile_versions.id"],
            name=op.f(
                "fk_candidate_skills_candidate_profile_version_id_candidate_profile_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_skill_id"],
            ["taxonomy_skills.id"],
            name=op.f("fk_candidate_skills_taxonomy_skill_id_taxonomy_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_skills")),
        sa.UniqueConstraint(
            "candidate_profile_version_id",
            "normalized_name",
            "skill_type",
            name=op.f("uq_candidate_skills_candidate_profile_version_id"),
        ),
    )
    op.create_table(
        "cluster_memberships",
        sa.Column("cluster_version_id", sa.UUID(), nullable=False),
        sa.Column("job_profile_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "membership_type",
            sa.Enum(
                "AUTOMATIC",
                "USER_ASSIGNED",
                "USER_EXCLUDED",
                name="membership_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "similarity_score IS NULL OR similarity_score BETWEEN 0 AND 1",
            name=op.f("ck_cluster_memberships_similarity_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["cluster_version_id"],
            ["cluster_versions.id"],
            name=op.f("fk_cluster_memberships_cluster_version_id_cluster_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f("fk_cluster_memberships_job_profile_version_id_job_profile_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_memberships")),
        sa.UniqueConstraint(
            "cluster_version_id",
            "job_profile_version_id",
            name=op.f("uq_cluster_memberships_cluster_version_id"),
        ),
    )
    op.create_table(
        "fit_evaluations",
        sa.Column("candidate_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("candidate_target_role_id", sa.UUID(), nullable=True),
        sa.Column("cluster_version_id", sa.UUID(), nullable=True),
        sa.Column("job_profile_version_id", sa.UUID(), nullable=True),
        sa.Column("evaluation_version", sa.Integer(), nullable=False),
        sa.Column("scoring_policy_version", sa.String(length=50), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("skill_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("experience_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("seniority_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("project_proof_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("interview_readiness_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "strengths",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "gaps",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "recommendations",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "((candidate_target_role_id IS NOT NULL)::integer + (cluster_version_id IS NOT NULL)::integer + (job_profile_version_id IS NOT NULL)::integer) = 1",
            name=op.f("ck_fit_evaluations_exactly_one_evaluation_target"),
        ),
        sa.CheckConstraint(
            "experience_score BETWEEN 0 AND 100",
            name=op.f("ck_fit_evaluations_experience_score_range"),
        ),
        sa.CheckConstraint(
            "interview_readiness_score BETWEEN 0 AND 100",
            name=op.f("ck_fit_evaluations_interview_readiness_score_range"),
        ),
        sa.CheckConstraint(
            "overall_score BETWEEN 0 AND 100", name=op.f("ck_fit_evaluations_overall_score_range")
        ),
        sa.CheckConstraint(
            "project_proof_score BETWEEN 0 AND 100",
            name=op.f("ck_fit_evaluations_project_proof_score_range"),
        ),
        sa.CheckConstraint(
            "seniority_score BETWEEN 0 AND 100",
            name=op.f("ck_fit_evaluations_seniority_score_range"),
        ),
        sa.CheckConstraint(
            "skill_score BETWEEN 0 AND 100", name=op.f("ck_fit_evaluations_skill_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_version_id"],
            ["candidate_profile_versions.id"],
            name=op.f("fk_fit_evaluations_candidate_profile_version_id_candidate_profile_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_target_role_id"],
            ["candidate_target_roles.id"],
            name=op.f("fk_fit_evaluations_candidate_target_role_id_candidate_target_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_version_id"],
            ["cluster_versions.id"],
            name=op.f("fk_fit_evaluations_cluster_version_id_cluster_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f("fk_fit_evaluations_job_profile_version_id_job_profile_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fit_evaluations")),
    )
    op.create_index(
        "ix_fit_evaluations_cluster_created",
        "fit_evaluations",
        ["cluster_version_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_fit_evaluations_job_created",
        "fit_evaluations",
        ["job_profile_version_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_fit_evaluations_target_role_created",
        "fit_evaluations",
        ["candidate_target_role_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "job_profile_interview_topics",
        sa.Column("job_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("normalized_topic", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f(
                "fk_job_profile_interview_topics_job_profile_version_id_job_profile_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_profile_interview_topics")),
        sa.UniqueConstraint(
            "job_profile_version_id",
            "normalized_topic",
            name=op.f("uq_job_profile_interview_topics_job_profile_version_id"),
        ),
    )
    op.create_table(
        "job_profile_responsibilities",
        sa.Column("job_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("normalized_category", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f(
                "fk_job_profile_responsibilities_job_profile_version_id_job_profile_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_profile_responsibilities")),
        sa.UniqueConstraint(
            "job_profile_version_id",
            "position",
            name=op.f("uq_job_profile_responsibilities_job_profile_version_id"),
        ),
    )
    op.create_table(
        "job_profile_skills",
        sa.Column("job_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_skill_id", sa.UUID(), nullable=True),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column(
            "skill_type",
            sa.Enum(
                "CORE",
                "SECONDARY",
                "WEAK_SIGNAL",
                "REQUIRED",
                "NICE_TO_HAVE",
                name="job_skill_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_job_profile_skills_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f("fk_job_profile_skills_job_profile_version_id_job_profile_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_skill_id"],
            ["taxonomy_skills.id"],
            name=op.f("fk_job_profile_skills_taxonomy_skill_id_taxonomy_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_profile_skills")),
        sa.UniqueConstraint(
            "job_profile_version_id",
            "normalized_name",
            "skill_type",
            name=op.f("uq_job_profile_skills_job_profile_version_id"),
        ),
    )
    op.create_table(
        "job_profile_tools",
        sa.Column("job_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_profile_version_id"],
            ["job_profile_versions.id"],
            name=op.f("fk_job_profile_tools_job_profile_version_id_job_profile_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_profile_tools")),
        sa.UniqueConstraint(
            "job_profile_version_id",
            "normalized_name",
            name=op.f("uq_job_profile_tools_job_profile_version_id"),
        ),
    )
    op.create_table(
        "market_signals",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("signal_key", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=False),
        sa.Column("change_from_previous", sa.Float(), nullable=True),
        sa.Column(
            "is_major_shift", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "frequency BETWEEN 0 AND 1", name=op.f("ck_market_signals_frequency_range")
        ),
        sa.CheckConstraint(
            "occurrence_count >= 0", name=op.f("ck_market_signals_occurrence_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["market_signal_snapshots.id"],
            name=op.f("fk_market_signals_snapshot_id_market_signal_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_signals")),
        sa.UniqueConstraint(
            "snapshot_id", "signal_type", "signal_key", name=op.f("uq_market_signals_snapshot_id")
        ),
    )
    op.create_table(
        "prep_plan_versions",
        sa.Column("prep_plan_id", sa.UUID(), nullable=False),
        sa.Column("based_on_cluster_version_id", sa.UUID(), nullable=True),
        sa.Column("based_on_fit_evaluation_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "SUPERSEDED",
                "ARCHIVED",
                name="plan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "plan_stage",
            sa.Enum(
                "BASELINE",
                "EARLY_SIGNAL",
                "DRAFT_CLUSTER_PLAN",
                "STABLE_PLAN",
                "WEEKLY_REFRESH",
                name="plan_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column("active_week", sa.Integer(), server_default="1", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "top_priorities",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "active_week BETWEEN 1 AND duration_weeks",
            name=op.f("ck_prep_plan_versions_active_week_valid"),
        ),
        sa.CheckConstraint(
            "duration_weeks > 0", name=op.f("ck_prep_plan_versions_duration_weeks_positive")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_prep_plan_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["based_on_cluster_version_id"],
            ["cluster_versions.id"],
            name=op.f("fk_prep_plan_versions_based_on_cluster_version_id_cluster_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["based_on_fit_evaluation_id"],
            ["fit_evaluations.id"],
            name=op.f("fk_prep_plan_versions_based_on_fit_evaluation_id_fit_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prep_plan_id"],
            ["prep_plans.id"],
            name=op.f("fk_prep_plan_versions_prep_plan_id_prep_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prep_plan_versions")),
        sa.UniqueConstraint(
            "prep_plan_id", "version", name=op.f("uq_prep_plan_versions_prep_plan_id")
        ),
    )
    op.create_index(
        "uq_prep_plan_versions_one_active",
        "prep_plan_versions",
        ["prep_plan_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "plan_change_proposals",
        sa.Column("prep_plan_id", sa.UUID(), nullable=False),
        sa.Column("source_plan_version_id", sa.UUID(), nullable=False),
        sa.Column("market_signal_snapshot_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                name="proposal_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("proposed_changes", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("major_shift_score", sa.Float(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "major_shift_score IS NULL OR major_shift_score BETWEEN 0 AND 1",
            name=op.f("ck_plan_change_proposals_major_shift_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["market_signal_snapshot_id"],
            ["market_signal_snapshots.id"],
            name=op.f("fk_plan_change_proposals_market_signal_snapshot_id_market_signal_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prep_plan_id"],
            ["prep_plans.id"],
            name=op.f("fk_plan_change_proposals_prep_plan_id_prep_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_plan_version_id"],
            ["prep_plan_versions.id"],
            name=op.f("fk_plan_change_proposals_source_plan_version_id_prep_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_change_proposals")),
    )
    op.create_index(
        "ix_plan_change_proposals_plan_status",
        "plan_change_proposals",
        ["prep_plan_id", "status"],
        unique=False,
    )
    op.create_table(
        "prep_tasks",
        sa.Column("prep_plan_version_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TODO",
                "IN_PROGRESS",
                "COMPLETED",
                "SKIPPED",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="TODO",
            nullable=False,
        ),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source_recommendation", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("priority > 0", name=op.f("ck_prep_tasks_priority_positive")),
        sa.CheckConstraint("week_number > 0", name=op.f("ck_prep_tasks_week_number_positive")),
        sa.ForeignKeyConstraint(
            ["prep_plan_version_id"],
            ["prep_plan_versions.id"],
            name=op.f("fk_prep_tasks_prep_plan_version_id_prep_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prep_tasks")),
    )
    op.create_index(
        "ix_prep_tasks_plan_week",
        "prep_tasks",
        ["prep_plan_version_id", "week_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prep_tasks_plan_week", table_name="prep_tasks")
    op.drop_table("prep_tasks")
    op.drop_index("ix_plan_change_proposals_plan_status", table_name="plan_change_proposals")
    op.drop_table("plan_change_proposals")
    op.drop_index(
        "uq_prep_plan_versions_one_active",
        table_name="prep_plan_versions",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("prep_plan_versions")
    op.drop_table("market_signals")
    op.drop_table("job_profile_tools")
    op.drop_table("job_profile_skills")
    op.drop_table("job_profile_responsibilities")
    op.drop_table("job_profile_interview_topics")
    op.drop_index("ix_fit_evaluations_target_role_created", table_name="fit_evaluations")
    op.drop_index("ix_fit_evaluations_job_created", table_name="fit_evaluations")
    op.drop_index("ix_fit_evaluations_cluster_created", table_name="fit_evaluations")
    op.drop_table("fit_evaluations")
    op.drop_table("cluster_memberships")
    op.drop_table("candidate_skills")
    op.drop_index(
        "ix_market_signal_snapshots_candidate_window", table_name="market_signal_snapshots"
    )
    op.drop_table("market_signal_snapshots")
    op.drop_index(
        "uq_job_profile_versions_one_active",
        table_name="job_profile_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("job_profile_versions")
    op.drop_table("cluster_skill_summaries")
    op.drop_index(
        "uq_candidate_profile_versions_one_active",
        table_name="candidate_profile_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("candidate_profile_versions")
    op.drop_index("ix_prep_plans_candidate_archived", table_name="prep_plans")
    op.drop_table("prep_plans")
    op.drop_index("ix_job_descriptions_candidate_created", table_name="job_descriptions")
    op.drop_table("job_descriptions")
    op.drop_index("ix_extraction_runs_document_started", table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index("ix_evidence_references_entity", table_name="evidence_references")
    op.drop_table("evidence_references")
    op.drop_index(
        "uq_cluster_versions_one_active",
        table_name="cluster_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("cluster_versions")
    op.drop_index("ix_user_corrections_entity", table_name="user_corrections")
    op.drop_table("user_corrections")
    op.drop_index("ix_source_documents_candidate_status", table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index("ix_clusters_candidate_status", table_name="clusters")
    op.drop_table("clusters")
    op.drop_index("ix_clustering_runs_candidate_started", table_name="clustering_runs")
    op.drop_table("clustering_runs")
    op.drop_table("candidate_target_roles")
    op.drop_table("taxonomy_occupation_skills")
    op.drop_table("skill_aliases")
    op.drop_index("ix_candidates_user_id", table_name="candidates")
    op.drop_table("candidates")
    op.drop_table("users")
    op.drop_table("taxonomy_skills")
    op.drop_table("taxonomy_occupations")
    # ### end Alembic commands ###
